spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/Employe
      username: root
      password: root

---
spring:
  config:
    activate:
      on-profile: test
  datasource: 
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@localhost:1521:orcl
      username: system
      password: root
      
---
spring:
  config:
     activate:
        on-profile: uat
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/Employe
      username: root
      password: root
      
---
spring:
  config:
    activate:
       on-profile: prod
  datasource:
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@localhost:1521:orcl
      username: system
      password: root
            